### PR TITLE
Sorry, I sent the wrong place, please delete it

### PR DESCRIPTION
**Pull request by 193769981**

### CODE REVIEW

**Comment by 193769981** [comment]
> Hello，I am also studying this article. Could you please tell me。can you add my wechart，it is 13131235830。Thank you very much!

**Comment by 193769981** [comment]
sorry

**Comment by 193769981** [comment]
1

**Comment by puzzlepaint** [comment]
I don't think I can delete a PR, just close it:
https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Pull request closed without merging**
